### ISSUE TITLE
Geolocation bug

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-personal-backend#56]
`GeocoderProviders.AUTO`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/ovos_local_backend/backend/decorators.py", line 83, in decorated_function
    resp = flask.make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/ovos_local_backend/backend/decorators.py", line 56, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ovos_local_backend/backend/external_apis.py", line 49, in geolocation
    return apis.geolocate(address)
  File "/usr/local/lib/python3.10/dist-packages/ovos_local_backend/utils/__init__.py", line 116, in geolocate
    "country": data["country"],
KeyError: 'country'
10.89.0.3 - - [17/May/2023 20:27:16] "GET /v1/geolocation?location=paris HTTP/1.1" 500 -
```

this nested location dict is haunting us 😛

**Comment by emphasize** [comment]
has to return

```python
return {"data": {
            "city": data["city"]["name"],                                              # name/code?
            "country": data["state"]["country"]["name"],            
            "latitude": float(data["coordinate"]["latitude"]),
            "longitude": float(data["coordinate"]["longitude"]),
            "region": data["state"]["name"],                                           # state != region
            "timezone": get_timezone(float(data["coordinate"]["latitude"]),
                                     float(data["coordinate"]["longitude"]))
        }}

**Comment by emphasize** [comment]
Note to me: `location["adress"]` is missing

**Comment by emphasize** [comment]
Kind of odd since a manual call to geocoder.osm("paris") and [geolocate](https://github.com/OpenVoiceOS/ovos-personal-backend/blob/5029f4bd5a97fafd47590ca35757f579e64f53d4/ovos_local_backend/utils/__init__.py#L112) should return
```
{'data': {
    'city': 'Paris',
    'country': 'France',
    'latitude': 48.8534951,
    'longitude': 2.3483915,
    'region': 'Île-de-France',
    'timezone': 'bla'
    }
}
```

**Comment by emphasize** [comment]
this is what i could log inside the docker
```
2023-05-17 20:58:22.736 - OVOS - ovos_local_backend.backend.external_apis:geolocation:49 - INFO - Location(ea): paris
2023-05-17 20:58:22.741 - OVOS - ovos_local_backend.utils.geolocate:engine:79 - INFO - Provider: OSM
2023-05-17 20:58:25.725 - OVOS - ovos_local_backend.utils:geolocate:114 - INFO - data: 
{'city': {
    'code': 'Paris', 
    'name': 'Paris',
    'state': {
        'code': 'Île-de-France',
        'name': 'Île-de-France',
        'country': {
            'code': 'France',
            'name': 'France'
        }
    }
},
'coordinate': {
     'latitude': 48.8534951,
     'longitude': 2.3483915
},
'timezone': {
     'dstOffset': 3600000,
     'offset': -21600000,
     'name': None,
     'code': 'Europe/Paris'
     }
}
```

**Comment by emphasize** [comment]
On a tangent, we should also perform a reverse search with personal backend. (if possible)
